# Copyright (c) Mixed Reality Toolkit Contributors
# Licensed under the BSD 3-Clause

# Build for PR validation

variables:
  - template: Config/settings.yaml

trigger: none # disable CI

stages:
  - stage: UnityValidation
    variables:
      - group: UnityVariables
    pool: 'Unity Interactive'
    jobs:
      - job: BuildStandaloneAndTest
        steps:
          - checkout: self
            fetchDepth: 3

          - template: Templates/unity.yaml
            parameters:
              Platform: Standalone
              RunTests: true
              UnityUsername: $(UnityUsername) 
              UnityPassword: $(UnityPassword)
              UnitySerial: $(UnitySerial)

      - job: BuildUWP
        condition: false
        steps:
          - checkout: self
            fetchDepth: 3

          - template: Templates/unity.yaml
            parameters:
              Platform: UWP
              UnityUsername: $(UnityUsername) 
              UnityPassword: $(UnityPassword)
              UnitySerial: $(UnitySerial)

      - job: BuildAndroid
        condition: false
        steps:
          - checkout: self
            fetchDepth: 3

          - template: Templates/unity.yaml
            parameters:
              Platform: Android
              UnityUsername: $(UnityUsername) 
              UnityPassword: $(UnityPassword)
              UnitySerial: $(UnitySerial)
